# Generated by Django 5.1.6 on 2026-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=600)),
                ('full_points', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Exams',
            },
        ),
    ]
