# Generated by Django 5.1.6 on 2026-05-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_order', models.IntegerField()),
                ('title', models.CharField(max_length=600)),
                ('details', models.TextField()),
                ('relation_to_question_no', models.CharField(blank=True, max_length=255, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exam_details', to='exams.exam')),
            ],
            options={
                'verbose_name_plural': "2. Exam's Details",
                'ordering': ['exam__exam_code', 'title_order'],
            },
        ),
    ]
