# Generated by Django 5.1.6 on 2026-05-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_academic_year_examdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_serial', models.IntegerField()),
                ('points', models.IntegerField()),
                ('question', models.TextField()),
                ('sample_answer', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='exam_question_answer', to='exams.exam')),
            ],
            options={
                'verbose_name_plural': "3. Exam's Question Answer",
                'ordering': ['exam__exam_code', 'question_serial'],
            },
        ),
    ]
