# Generated by Django 5.1.6 on 2026-06-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='use_for_grading_guideline',
            field=models.BooleanField(default=False),
        ),
    ]
