# Generated by Django 5.1.6 on 2026-06-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examdetails_use_for_grading_guideline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetails',
            name='use_for_grading_guideline',
        ),
        migrations.AddField(
            model_name='examquestionanswer',
            name='grading_guideline',
            field=models.TextField(null=True),
        ),
    ]
