# Generated by Django 5.1.6 on 2026-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_examdetails_use_for_grading_guideline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestionanswer',
            name='rubric_titles',
            field=models.TextField(null=True),
        ),
    ]
