# Generated by Django 5.1.6 on 2026-05-09 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0003_examquestionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('question_serial', models.IntegerField()),
                ('answer', models.TextField()),
                ('llm_score_points', models.FloatField(null=True)),
                ('llm_model', models.CharField(blank=True, max_length=600, null=True)),
                ('llm_feedback', models.TextField(null=True)),
                ('llm_start_time', models.FloatField(null=True)),
                ('llm_end_time', models.FloatField(null=True)),
                ('llm_response_in_sec', models.FloatField(null=True)),
                ('llm_response_raw', models.TextField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_answer', to='exams.exam')),
            ],
            options={
                'verbose_name_plural': '1. StudentAnswers',
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('total_point', models.FloatField()),
                ('grade', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_grade', to='exams.exam')),
            ],
            options={
                'verbose_name_plural': '2. StudentGrade',
            },
        ),
    ]
