# Generated by Django 5.1.6 on 2026-05-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='llm_has_response',
            field=models.BooleanField(null=True),
        ),
    ]
