# Generated by Django 5.1.6 on 2026-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_studentanswer_llm_has_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='total_point',
            field=models.FloatField(null=True),
        ),
    ]
