# Generated by Django 5.1.6 on 2026-05-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examquestionanswer'),
        ('grading', '0003_alter_studentgrade_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'verbose_name_plural': '3. StudentGrade'},
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_input_token',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_output_tokens',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_response_eval_duration_sec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_response_prompt_eval_duration_sec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_response_total_duration_sec',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_used_alternative_approach',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='StudentAnswerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('is_from_guideline', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_answer_details_exam', to='exams.exam')),
                ('student_answer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_answer_details_answer', to='grading.studentanswer')),
            ],
            options={
                'verbose_name_plural': '2. StudentAnswerDetails',
            },
        ),
    ]
