# Generated by Django 5.1.6 on 2026-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_alter_studentgrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='llm_context_raw',
            field=models.TextField(null=True),
        ),
    ]
