# Generated by Django 5.1.6 on 2026-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_studentanswer_llm_context_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('exam_id', models.IntegerField()),
                ('student_answer_id', models.IntegerField()),
                ('question_serial', models.IntegerField()),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('llm_model', models.CharField(blank=True, max_length=600, null=True)),
                ('llm_feedback', models.TextField(null=True)),
                ('llm_start_time', models.FloatField(null=True)),
                ('llm_end_time', models.FloatField(null=True)),
                ('llm_response_in_sec', models.FloatField(null=True)),
                ('llm_response_raw', models.TextField(null=True)),
                ('llm_input_token', models.IntegerField(null=True)),
                ('llm_output_tokens', models.IntegerField(null=True)),
                ('llm_response_total_duration_sec', models.FloatField(null=True)),
                ('llm_response_prompt_eval_duration_sec', models.FloatField(null=True)),
                ('llm_response_eval_duration_sec', models.FloatField(null=True)),
                ('llm_context_raw', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': '10. LlmLogs',
            },
        ),
    ]
