# Generated by Django 5.1.6 on 2026-06-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_llmlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmlog',
            options={'verbose_name_plural': '4. LlmLogs'},
        ),
        migrations.RemoveField(
            model_name='llmlog',
            name='student_answer_id',
        ),
    ]
