# Generated by Django 5.1.6 on 2026-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_alter_llmlog_options_remove_llmlog_student_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmlog',
            name='llm_fix_rubric_points',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='llmlog',
            name='llm_fix_rubric_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='llmlog',
            name='llm_fix_score_points',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_fix_rubric_points',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_fix_rubric_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='llm_fix_score_points',
            field=models.BooleanField(null=True),
        ),
    ]
