# Generated by Django 5.1.6 on 2026-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_llmlog_llm_fix_rubric_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmlog',
            name='llm_score_points',
            field=models.FloatField(null=True),
        ),
    ]
