# Generated by Django 5.1.6 on 2026-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_llmlog_llm_score_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerdetails',
            name='is_fix_llm_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswerdetails',
            name='llm_score',
            field=models.FloatField(default=0),
        ),
    ]
